name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  integration-tests:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          profile: Nexus 6
          script: |
            adb shell settings put global hidden_api_policy_p_apps 1
            adb shell settings put global hidden_api_policy_pre_p_apps 1
            adb shell settings put global hidden_api_policy 1
            ./gradlew connectedAndroidTest
            ./gradlew pullDebugAndroidTestScreenshots
      - name: Copy App Test Results
        if: always()
        run: |
          mkdir -p app-screenshot-tests
          find . -type f -wholename "./app/build/screenshotsDebugAndroidTest/*" -exec cp -r {} app-screenshot-tests/ \;
      - name: Copy Compose Preference Test Results
        if: always()
        run: |
          mkdir -p compose-preference-screenshot-tests
          find . -type f -wholename "./compose-preference/build/screenshotsDebugAndroidTest/*" -exec cp -r {} compose-preference-screenshot-tests/ \;
      - name: Upload App Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: app-screenshot-test-results
          path: app-screenshot-tests
      - name: Upload Compose Preference Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: compose-preference-screenshot-test-results
          path: compose-preference-screenshot-tests
