name: Nightly

on:
  push:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew :app:connectedAndroidTest
      - name: Copy Test Results
          if: always()
          run: |
            mkdir -p screenshot-tests
            find . -type f -regex ".*/build/screenshotsDebugAndroidTest/*" -exec cp {} screenshot-tests/ \;
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: screenshot-test-results
          path: screenshot-tests
